-- StudyNest Database Seeder - Modules Data

-- Semester 2
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Engineering Mathematics II', 'MATH201', 2, 'Advanced mathematical concepts including differential equations, linear algebra, and complex analysis for engineering applications.', '/images/sem2/math2.png', 'https://drive.google.com/math2', 'https://youtu.be/math2', 'https://www.geeksforgeeks.org/engineering-mathematics/');
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Physics', 'PHY201', 2, 'Fundamental principles of physics including mechanics, thermodynamics, electromagnetism, and modern physics.', '/images/sem2/physics.png', 'https://drive.google.com/physics', 'https://youtu.be/physics', 'https://www.geeksforgeeks.org/physics/');
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Programming in C', 'CS201', 2, 'Introduction to C programming language covering syntax, data structures, pointers, and memory management.', '/images/sem2/c-programming.png', 'https://drive.google.com/c-prog', 'https://youtu.be/c-prog', 'https://www.geeksforgeeks.org/c-programming-language/');
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Digital Electronics', 'ECE201', 2, 'Study of digital circuits, logic gates, Boolean algebra, combinational and sequential circuits.', '/images/sem2/digital.png', 'https://drive.google.com/digital', 'https://youtu.be/digital', 'https://www.geeksforgeeks.org/digital-electronics-logic-design-tutorials/');
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Engineering Graphics', 'ME201', 2, 'Technical drawing, orthographic projections, isometric views, and CAD fundamentals for engineering design.', '/images/sem2/graphics.png', 'https://drive.google.com/graphics', 'https://youtu.be/graphics', 'https://www.geeksforgeeks.org/engineering-graphics/');

-- Semester 3
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Data Structures', 'CS301', 3, 'Comprehensive study of data structures including arrays, linked lists, stacks, queues, trees, and graphs.', '/images/sem3/ds.png', 'https://drive.google.com/ds', 'https://youtu.be/ds', 'https://www.geeksforgeeks.org/data-structures/');
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Discrete Mathematics', 'MATH301', 3, 'Mathematical structures and logic including set theory, graph theory, combinatorics, and number theory.', '/images/sem3/dm.png', 'https://drive.google.com/dm', 'https://youtu.be/dm', 'https://www.geeksforgeeks.org/discrete-mathematics-tutorial/');
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Computer Organization', 'CS302', 3, 'Computer architecture, instruction sets, memory hierarchy, I/O systems, and processor design.', '/images/sem3/co.png', 'https://drive.google.com/co', 'https://youtu.be/co', 'https://www.geeksforgeeks.org/computer-organization-and-architecture-tutorials/');
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Object Oriented Programming', 'CS303', 3, 'OOP concepts using Java including classes, objects, inheritance, polymorphism, and design patterns.', '/images/sem3/oop.png', 'https://drive.google.com/oop', 'https://youtu.be/oop', 'https://www.geeksforgeeks.org/object-oriented-programming-oops-concept-in-java/');
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Database Management Systems', 'CS304', 3, 'Database design, SQL, normalization, transactions, concurrency control, and database administration.', '/images/sem3/dbms.png', 'https://drive.google.com/dbms', 'https://youtu.be/dbms', 'https://www.geeksforgeeks.org/dbms/');

-- Semester 4
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Operating Systems', 'CS401', 4, 'OS concepts including process management, memory management, file systems, and synchronization.', '/images/sem4/os.png', 'https://drive.google.com/os', 'https://youtu.be/os', 'https://www.geeksforgeeks.org/operating-systems/');
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Design and Analysis of Algorithms', 'CS402', 4, 'Algorithm design techniques, complexity analysis, sorting, searching, and graph algorithms.', '/images/sem4/daa.png', 'https://drive.google.com/daa', 'https://youtu.be/daa', 'https://www.geeksforgeeks.org/fundamentals-of-algorithms/');
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Computer Networks', 'CS403', 4, 'Network protocols, OSI model, TCP/IP, routing, switching, and network security fundamentals.', '/images/sem4/cn.png', 'https://drive.google.com/cn', 'https://youtu.be/cn', 'https://www.geeksforgeeks.org/computer-network-tutorials/');
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Software Engineering', 'CS404', 4, 'Software development lifecycle, requirements analysis, design patterns, testing, and project management.', '/images/sem4/se.png', 'https://drive.google.com/se', 'https://youtu.be/se', 'https://www.geeksforgeeks.org/software-engineering/');
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Web Technologies', 'CS405', 4, 'HTML, CSS, JavaScript, frontend frameworks, backend development, and web application architecture.', '/images/sem4/web.png', 'https://drive.google.com/web', 'https://youtu.be/web', 'https://www.geeksforgeeks.org/web-development/');

-- Semester 5
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Theory of Computation', 'CS501', 5, 'Automata theory, formal languages, Turing machines, computability, and complexity theory.', '/images/sem5/toc.png', 'https://drive.google.com/toc', 'https://youtu.be/toc', 'https://www.geeksforgeeks.org/theory-of-computation-automata-tutorials/');
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Compiler Design', 'CS502', 5, 'Lexical analysis, parsing, syntax-directed translation, code generation, and optimization techniques.', '/images/sem5/cd.png', 'https://drive.google.com/cd', 'https://youtu.be/cd', 'https://www.geeksforgeeks.org/compiler-design-tutorials/');
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Artificial Intelligence', 'CS503', 5, 'AI fundamentals including search algorithms, knowledge representation, machine learning basics, and expert systems.', '/images/sem5/ai.png', 'https://drive.google.com/ai', 'https://youtu.be/ai', 'https://www.geeksforgeeks.org/artificial-intelligence/');
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Computer Graphics', 'CS504', 5, 'Graphics primitives, transformations, 3D modeling, rendering techniques, and animation fundamentals.', '/images/sem5/cg.png', 'https://drive.google.com/cg', 'https://youtu.be/cg', 'https://www.geeksforgeeks.org/computer-graphics/');
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Cryptography', 'CS505', 5, 'Encryption algorithms, cryptographic protocols, digital signatures, and network security applications.', '/images/sem5/crypto.png', 'https://drive.google.com/crypto', 'https://youtu.be/crypto', 'https://www.geeksforgeeks.org/cryptography/');

-- Semester 6
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Machine Learning', 'CS601', 6, 'Supervised and unsupervised learning, neural networks, deep learning, and ML model evaluation.', '/images/sem6/ml.png', 'https://drive.google.com/ml', 'https://youtu.be/ml', 'https://www.geeksforgeeks.org/machine-learning/');
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Cloud Computing', 'CS602', 6, 'Cloud service models, virtualization, distributed systems, AWS/Azure platforms, and cloud security.', '/images/sem6/cloud.png', 'https://drive.google.com/cloud', 'https://youtu.be/cloud', 'https://www.geeksforgeeks.org/cloud-computing/');
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Big Data Analytics', 'CS603', 6, 'Hadoop, MapReduce, Spark, data mining techniques, and large-scale data processing frameworks.', '/images/sem6/bigdata.png', 'https://drive.google.com/bigdata', 'https://youtu.be/bigdata', 'https://www.geeksforgeeks.org/big-data-analytics/');
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Internet of Things', 'CS604', 6, 'IoT architecture, sensors, embedded systems, communication protocols, and IoT application development.', '/images/sem6/iot.png', 'https://drive.google.com/iot', 'https://youtu.be/iot', 'https://www.geeksforgeeks.org/introduction-to-internet-of-things-iot-set-1/');
INSERT INTO modules (name, code, semester, description, image_url, pdf_url, video_link, external_links) VALUES ('Cyber Security', 'CS605', 6, 'Security threats, vulnerability assessment, penetration testing, incident response, and security best practices.', '/images/sem6/security.png', 'https://drive.google.com/security', 'https://youtu.be/security', 'https://www.geeksforgeeks.org/cyber-security/');
